Update 20200207 Using Powershell to automate Linux, macOS, and Window…
LCTT/TranslateProject pull request #23762
Opened 2021-11-07 09:44 UTC by FigaroCao

…s processes.md

2021-11-07 16:28 UTC, wxy requested changes
请移动到translated 目录

2021-11-09 01:26 UTC, wxy commented
@FigaroCao 请移动一下，另外请修改你的 qq 群内的 id，要不我 at 不到你

2021-11-10 00:54 UTC, FigaroCao commented
> @FigaroCao 请移动一下，另外请修改你的 qq 群内的 id，要不我 at 不到你

我在群内的id是译者-FigaroCao

2021-11-10 01:10 UTC, wxy approved these changes

2021-11-14 01:22 UTC, closed without merging