申领原文
LCTT/TranslateProject pull request #25691
Opened 2022-05-17 17:42 UTC by yesimmia

2022-05-17 17:43 UTC, yesimmia commented
being translated by yesimmia

2022-05-18 01:10 UTC, wxy requested changes
1、请在翻译申请时不要移动
2、翻译后，移动到 translated 下对应目录

2022-05-19 08:14 UTC, yesimmia commented
已修改

2022-05-19 10:04 UTC, wxy approved these changes

2022-05-19 10:05 UTC, merged