20210104 docker compose  a nice way to set up a dev environment.md
LCTT/TranslateProject pull request #26169
Opened 2022-06-22 07:19 UTC by turbokernel

2022-06-22 07:33 UTC, wxy approved these changes

2022-06-22 07:33 UTC, wxy commented
标记在此，暂不合并，待校对完后再合并。

2022-06-22 08:21 UTC, wxy requested changes
等待校对完成

2022-06-23 01:36 UTC, wxy commented
@turbokernel 因为累积的提交在一个未合并的 PR 中，所以我不知道你是否完成了校对，这种情况下，你完成后可以写个备注说明一下。

2022-06-23 04:16 UTC, turbokernel commented
> @turbokernel 因为累积的提交在一个未合并的 PR 中，所以我不知道你是否完成了校对，这种情况下，你完成后可以写个备注说明一下。

已完成。

2022-06-23 04:18 UTC, turbokernel reviewed
已完成

2022-06-23 05:21 UTC, wxy approved these changes

2022-06-23 05:21 UTC, merged