translating
LCTT/TranslateProject pull request #26703
Opened 2022-08-05 19:31 UTC by yjacks

2022-08-05 19:55 UTC, yjacks commented
原来在提交了PR后的提交也会被合并么。。。

2022-08-06 09:17 UTC, lkxed commented on translated/tech/20220626 An open source project that opens the internet for all.md
> +W3C 的网页设计无障碍化指南（WCAG）设定了无障碍标准。Equalify 和其它的组织，包括<rust>合众国政府<rt>US Federal Government</rt></rust>，使用 WCAG 来定义望远的无障碍化。我们审视的的网站越多，我们就越能理解WCAG标准的缺点和潜力。
这个标签是 `ruby` 而非 `rust`

2022-08-06 09:18 UTC, lkxed commented on translated/tech/20220626 An open source project that opens the internet for all.md
> +一个为了使因特网开放向所有人的开源项目
我们一般的语序会说 “为了使因特网向所有人开放”

2022-08-06 09:19 UTC, lkxed commented on translated/tech/20220626 An open source project that opens the internet for all.md
> +这个平台允许使用者们运行大量的无障碍操作在数以千计的网页。通过用最新的版本，用户还可以过滤无数的警告，创建一个对他们来说有意义的统计仪表盘。
第一句，也是语序问题，应该是 “在数以千计的网页上运行大量的无障碍操作”

2022-08-06 09:22 UTC, lkxed commented on translated/tech/20220626 An open source project that opens the internet for all.md
> +花点时间看我们的Github，这样你能更多的了解这个产品。[README][3]提供了分布教程，它关于如何开始维护和使用 Equalify。
中英文之间、中英文和数字之间，应该加一个空格，如 Github、README，还有下一段的 96.8%、The WebAIM Million 等。检查全文，看看还有没有遗漏。

2022-08-06 09:25 UTC, lkxed requested changes
从一些用词上可以看出你有认真翻译，但是还有进步的空间，继续加油，可以参考 @wxy @geekpi 以往的翻译，向他们学习。

2022-08-06 09:28 UTC, lkxed commented
> 原来在提交了PR后的提交也会被合并么。。。

对的，如果 PR 还未被关闭，那么所有新加入到这个 PR 分支的 commits 都会成为本次 PR 的一部分。

2022-08-06 14:12 UTC, lkxed approved these changes

2022-08-06 14:12 UTC, merged