Translating
LCTT/TranslateProject pull request #26735
Opened 2022-08-09 03:35 UTC by yjacks

2022-08-09 05:19 UTC, lkxed commented
@yjacks 你忘记删除 `sources` 里的译文啦，翻译完成后是将译文**移动到** `translated` 目录。

2022-08-09 14:12 UTC, yjacks commented
我至今看不懂为什么我会犯这么离谱的错误，，，

2022-08-09 14:29 UTC, lkxed commented
> 我至今看不懂为什么我会犯这么离谱的错误，，，

这没什么离谱的，忘记了而已～

2022-08-09 14:51 UTC, lkxed requested changes
同学，我想给你一些建议：

把它放上一晚，明天抽空读一遍自己的译文，修改一些你觉得 缺失 / 拗口 / 不顺 的地方。我个人认为：为了读者有好体验，能读着通顺、不费劲，我们啰嗦一些、加些惯用语，也无妨。

读的时候，不要把它当作篇自己写的译文，而是当作你平时看的、别人写的一篇文章，从这个视角看看？

2022-08-10 16:17 UTC, lkxed approved these changes
有了不小的进步，为你点赞👍！

2022-08-10 16:17 UTC, lkxed approved these changes

2022-08-10 16:18 UTC, merged