完成了翻译
LCTT/TranslateProject pull request #27912
Opened 2022-11-12 09:00 UTC by littlebirdnest

2022-11-12 10:13 UTC, lkxed requested changes
@littlebirdnest 你忘记把译文移动到 `translated/tech` 下啦！

2022-11-12 10:17 UTC, lkxed commented on translated/tech/20221021.3 ⭐️ How to Install AWS CLI on Linux Step-by-Step.md
>  if(typeof ez_ad_units != 'undefined'){ez_ad_units.push([[250,250],'linuxtechi_com-box-4','ezslot_8',260,'0','0'])};__ez_fad_position('div-gpt-ad-linuxtechi_com-box-4-0');
这一段是我选题时候的失误，请删除它

2022-11-12 10:18 UTC, lkxed commented on translated/tech/20221021.3 ⭐️ How to Install AWS CLI on Linux Step-by-Step.md
>  if(typeof ez_ad_units != 'undefined'){ez_ad_units.push([[250,250],'linuxtechi_com-banner-1','ezslot_9',360,'0','0'])};__ez_fad_position('div-gpt-ad-linuxtechi_com-banner-1-0');
同上，这一段也是我选题的失误，请删除

2022-11-12 10:19 UTC, lkxed reviewed
另外，我想提醒注意一下，翻译完成后请自己读一遍，你的译文有多处不大通顺的地方，读一遍就能够发现并改正大多数～

2022-11-12 11:55 UTC, wxy commented
@littlebirdnest 另外请创建新分支提交贡献更好。

2022-11-13 02:02 UTC, Cubik65536 commented on translated/tech/20221021.3 ⭐️ How to Install AWS CLI on Linux Step-by-Step.md
> +译者：[littlebirdnest](https://github.com/译者ID)
```suggestion
译者：[littlebirdnest](https://github.com/littlebirdnest)
```

其实还需提醒一下记得把链接也改为指向你的 GitHub Profile 的地址

2022-11-15 07:41 UTC, merged