translated "20210209 Understanding Linus-s Law for open source security" and checked
LCTT/TranslateProject pull request #28191
Opened 2022-12-11 07:06 UTC by CanYellow

2022-12-11 16:00 UTC, lkxed requested changes
我们会检查 PR 的格式，大概来说的规则是“一个 PR 里只允许操作一篇文章”，因此，要申请翻译新的文章时，请新建分支操作～
对于这个 PR 而言，因为你已经完成了一篇的翻译，所以只需要 revert 新一篇的申请，检查就能通过了～

2022-12-11 23:59 UTC, CanYellow commented
sorry
我看过wiki了，本来只操作了一篇文章，
可以我PR以后，继续在master分支里操作了，我也没注意另一篇文章改了什么，现在已经恢复了，请您确认

不好意思，给您添麻烦了

2022-12-12 00:08 UTC, wxy approved these changes

2022-12-12 00:09 UTC, wxy commented
> sorry 我看过wiki了，本来只操作了一篇文章， 可以我PR以后，继续在master分支里操作了，我也没注意另一篇文章改了什么，现在已经恢复了，请您确认
> 
> 不好意思，给您添麻烦了

没事的，以后每篇文章都创建一个新分支，就能避免这个问题啦。
感谢您的贡献！

2022-12-12 02:45 UTC, closed without merging