翻译完成
LCTT/TranslateProject pull request #28578
Opened 2023-02-07 03:30 UTC by cool-summer-021

2023-02-07 03:44 UTC, wxy requested changes
请移动一下

2023-02-07 07:11 UTC, cool-summer-021 commented
> 请移动一下

怎么操作？为啥要移动？

2023-02-07 08:26 UTC, wxy commented
> > 请移动一下
> 
> 怎么操作？为啥要移动？

翻译后的文件要从 sources 下移动到 translated 下啊，你忘记啦？

2023-02-08 03:55 UTC, wxy approved these changes

2023-02-08 03:55 UTC, merged